project:
  type: website

website:
  title: "Quinn He Blog"
  navbar:
    right:
      - text: "About Me"
      - file: about.qmd
      - icon: github
        href: https://github.com/quinn556
      - icon: linkedin
        href: https://www.linkedin.com/in/quinnhe/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

