project:
  type: website

website:
  title: "Quinn He's Website"
  navbar:
    background: "#881c1c"
    right:
      - text: "About Me"
      - file: about.qmd
      - icon: github
        href: https://github.com/quinn556
      - text: linkedin
        href: https://www.linkedin.com/in/quinnhe/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

